### ISSUE TITLE
Whats the issue?

### ISSUE THREAD

**Issue by Er1807** [Minagoroshi/VRChat-Openbullet2-Config#1]
What is the issue with the login endpoint.
Looked at the file and it just looks like a credential checker/ or a way to login with a user and password and get that users infomation. Looks like the intended behavior?

**Comment by ghost** [comment]
it is open for credentials stuffing type attacks
there is the problem

**Comment by Minagoroshi** [comment]
> What is the issue with the login endpoint. Looked at the file and it just looks like a credential checker/ or a way to login with a user and password and get that users infomation. Looks like the intended behavior?

API Security Standards are a MUST and leaving your authorization endpoint open to credential stuffing attacks is no where near the standards expected in modern web applications. Allowing an authorization endpoint to be so easily accesible opens up many more issues aswell, hence the reason we see bots running rampant. A better course of action if they wish to allow stuff like vrcx to exist is to provide API keys on a name to name basis with trusted content creators instead of allowing everyone and their mom have open access to the entire API.

One fix would be to implement a captcha on login but this isn't fullproof and is also detrimental to user-experience.

A client side generated nonce that is checked on the backend to ensure request validity would do just fine and isn't hard to implement
